config/routes.rb
Taskbox::Application.routes.draw do
  constraints :format => :html do
    root to: "users#index"

    resources :users, except: [:show] do
      resources :tasks, except: [:new, :show] do
        member do
          put :close
          put :reopen
        end
      end
    end
  end

  constraints :format => :json do
    resources :users, only: [:index, :show] do
      resources :tasks, only: [:index, :show] do
        member do
          put :close
          put :reopen
        end
      end
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :title

  validates :title, :user_id, presence: true

  def close
    update_attribute(:closed, true)
  end

  def reopen
    update_attribute(:closed, false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  attr_accessible :name, :surname

  validates :name, presence: true, length: {maximum: 50}
  validates :surname, presence: true, length: {maximum: 150}

  def full_name
    "#{name} #{surname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :json

  def index
    @user = get_user(params[:user_id])
  end

  def show
    @task = get_task(params[:id])
  end

  def create
    user = get_user(params[:user_id])
    task = user.tasks.new(params[:task])

    if task.save
      flash[:notice] = "Task added"
    else
      flash[:error] = "Task can't be added"
    end
    redirect_to user_tasks_path(user)
  end

  def edit
    @task = get_task(params[:id])
  end

  def update
    @task = get_task(params[:id])

    if @task.update_attributes(params[:task])
      redirect_to user_tasks_path(@task.user), notice: "Task updated"
    else
      render :edit
    end
  end

  def destroy
    task = get_task(params[:id])
    task.destroy
    redirect_to user_tasks_path(task.user), notice: "Task deleted"
  end

  def close
    task = get_task(params[:id])
    task.close
    respond_to do |format|
      format.html { redirect_to user_tasks_path(task.user), notice: "Task closed" }
      format.json { head(:ok) }
    end
  end

  def reopen
    task = get_task(params[:id])
    task.reopen

    respond_to do |format|
      format.html {redirect_to user_tasks_path(task.user), notice: "Task has been reopened"}
      format.json { head(:ok) }
    end
  end

  private
  def get_user(user_id)
    User.find(user_id, include: :tasks)
  end

  def get_task(task_id)
    Task.find(params[:id], include: :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    @user = get_user(params[:id])
    respond_with(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    if @user.save
      redirect_to users_path, notice: 'New user has been created'
    else
      render :new
    end
  end

  def edit
    @user = get_user(params[:id])
  end

  def update
    @user = get_user(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to users_path, notice: 'The user has been updated'
    else
      render :edit
    end
  end

  def destroy
    @user = get_user(params[:id])
    @user.destroy

    redirect_to users_path, notice: 'The user has been deleted'
  end

  private
  def get_user(user_id)
    User.find(user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Taskbox" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Taskbox", root_path, class: 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Users", users_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Taskbox</h3>
                <p>
                  An insanely simple tasks manager
                </p>
                <ul class="nav nav-list">
                  <li class="nav-header">Check the source at</li>
                  <li><%= link_to "bitbucket", "https://bitbucket.org/csaura/taskbox"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/tasks/_task.html.erb
<%= content_tag_for :li, task do %>
  <%= task.title %>
  <div>
    <% if task.closed? -%>
      <%= link_to 'reopen', reopen_user_task_path(user_id: task.user_id, id: task.id), method: :put, class: 'btn btn-warning btn-mini' %>
    <% else -%>
      <%= link_to 'close', close_user_task_path(user_id: task.user_id, id: task.id), method: :put, class: 'btn btn-success btn-mini' %>
    <% end -%>
    <%= link_to 'edit', edit_user_task_path(user_id: task.user_id, id: task.id), class: 'btn btn-mini' %>
    <%= link_to 'delete', user_task_path(user_id: task.user_id, id: task.id), method: :delete, class: 'btn btn-danger btn-mini' %>
  </div>
<% end -%>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_for [@task.user, @task] do |f| %>
  <% if @task.errors.any? -%>
    <div class="alert alert-error">
      <h2><%= pluralize(@task.errors.size, 'error') %></h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| -%>
          <li><%= msg %></li>
        <% end -%>
      </ul>
    </div>
  <% end -%>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'span6' %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'span6' %>
  </div>
  <%= link_to 'cancel', user_tasks_path(@task.user), class: 'btn' %>
  <%= f.submit 'Update Task', class: 'btn btn-primary'%>
<% end -%>

app/views/tasks/index.html.erb
<h1><%= @user.full_name %> Tasks</h1>

<%= content_tag(:p, notice, id: 'notice', class: 'alert alert-success') if notice %>
<%= content_tag(:p, flash[:error], id: 'error', class: 'alert alert-error') if flash[:error] %>

<%= form_tag user_tasks_path(@user), id: "new_task", class: 'form-inline' do %>
  <%= text_field :task, :title, class: 'input-xlarge' %>
  <%= submit_tag "Create Task", class: 'btn btn-inverse' %>
<% end -%>
<div id="user_tasks">
  <ul class="unstyled">
    <%= render @user.tasks %>
  </ul>
</div>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <% if user.errors.any? -%>
    <div class="alert alert-error">
      <h2><%= pluralize(user.errors.size, 'error') %></h2>
      <ul>
        <% user.errors.full_messages.each do |msg| -%>
          <li><%= msg %></li>
        <% end -%>
      </ul>
    </div>
  <% end -%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end -%>
<%= link_to 'Cancel', users_path, class: 'btn' %>

app/views/users/_user.html.erb
<%= content_tag_for :li, user do %>
  <%= user.full_name %>
  <div>
    <%= link_to 'tasks', user_tasks_path(user), class: 'btn btn-info btn-mini' %>
    <%= link_to 'edit', edit_user_path(user), class: 'btn btn-mini' %>
    <%= link_to 'delete', user, method: :delete, class: 'btn btn-danger btn-mini' %>
  </div>
<% end -%>

app/views/users/edit.html.erb
<h1>Editing <%= @user.full_name %> user</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users List</h1>
<%= content_tag(:p, notice, id: 'notice', class: 'alert alert-success') if notice %>
<div id="users">
  <ul class="unstyled">
    <%= render @users %>
  </ul>
</div>
<%= link_to 'new user', new_user_path, id: 'new_user', class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form', user: @user %>